import { mkdir, writeFile, copyFile, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import config from '../site.config.mjs';
import { esc, header, hero, processSection, startSection, faq, contact, footer } from '../src/components.mjs';
const origin = config.origin ? new URL(config.origin).origin : '';
const canonical = origin ? origin + config.path : '';
const css = await Promise.all(['src/style.css', 'src/experience.css', 'src/glass.css', 'src/atmosphere.css'].map(file => readFile(file, 'utf8'))).then(parts => parts.join('\n'));
const js = await readFile('src/app.js');
const assetVersion = createHash('sha256').update(css).update(js).digest('hex').slice(0,12);
const html = `<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0B0B0D"><title>${esc(config.title)}</title><meta name="description" content="${esc(config.description)}"><meta name="robots" content="${config.indexable && origin?'index, follow':'noindex, nofollow'}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="NOVA lab"><meta property="og:title" content="${esc(config.title)}"><meta property="og:description" content="${esc(config.description)}">${canonical ? `<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}${config.ogImage && origin?`<meta property="og:image" content="${esc(new URL(config.ogImage, origin).href)}">`:''}<link rel="icon" type="image/png" href="/assets/nova-logo.png"><link rel="stylesheet" href="/assets/style.css?v=${assetVersion}"><script type="module" src="/assets/app.js?v=${assetVersion}"></script></head><body>${header()}<main id="main">${hero()}${processSection()}${startSection()}${faq()}${contact(config)}</main>${footer(config)}<noscript><div class="noscript-note">Автопрокрутка требует JavaScript. Все примеры доступны ниже.</div></noscript></body></html>`;
const introBootstrap = `<script>(()=>{try{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;if(sessionStorage.getItem('nova-intro-seen')&&!new URLSearchParams(location.search).has('intro'))return;}catch{}document.documentElement.classList.add('intro-pending');window.novaIntroFallback=setTimeout(()=>document.documentElement.classList.remove('intro-pending'),8000);})();</script>`;
const introMarkup = `<div class="brand-intro" id="brand-intro" role="dialog" aria-modal="true" aria-label="Заставка NOVA lab"><video muted playsinline preload="none" aria-hidden="true" tabindex="-1" disablepictureinpicture></video><button type="button" class="intro-skip">Пропустить заставку ↗</button></div>`;
const pageHtml = html.replace('</head>', introBootstrap + '</head>').replace('<body>', '<body>' + introMarkup);
await mkdir('dist/services/max-bots', { recursive: true });
await mkdir('dist/assets', { recursive: true });
await writeFile('dist/services/max-bots/index.html', pageHtml);
await writeFile('dist/index.html', pageHtml);
await writeFile('dist/assets/style.css', css);
await copyFile('src/app.js', 'dist/assets/app.js');
await copyFile('src/intro.js', 'dist/assets/intro.js');
await copyFile('public/.htaccess', 'dist/.htaccess');
await copyFile('public/assets/nova-intro.mp4', 'dist/assets/nova-intro.mp4');
await copyFile('public/assets/nova-hero-endframe.png', 'dist/assets/nova-hero-endframe.png');
for (const asset of ['nova-logo.png','manrope-cyrillic.woff2','manrope-latin.woff2','OFL-Manrope.txt','unbounded-cyrillic.woff2','unbounded-latin.woff2','OFL-Unbounded.txt']) await copyFile('public/assets/' + asset, 'dist/assets/' + asset);
await writeFile('dist/robots.txt', config.indexable && origin ? `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n` : 'User-agent: *\nDisallow: /\n');
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${canonical ? `<url><loc>${esc(canonical)}</loc></url>` : ''}</urlset>`);
console.log('Built NOVA lab → dist/ (root and /services/max-bots/)');
