import { scenarios } from './scenarios.mjs';
export const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name, cls = '') {
  const paths = { arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>', diagonal:'<path d="M6 18 18 6M6 6h12v12"/>', check:'<path d="m5 12 4 4L19 6"/>', plus:'<path d="M12 5v14M5 12h14"/>', inbox:'<path d="M4 4h16v16H4zM4 13h5l1 3h4l1-3h5"/>', calendar:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4m8-4v4M4 10h16m-11 4h2m2 0h2"/>', file:'<path d="M5 3h9l5 5v13H5zM14 3v6h5M8 13h8m-8 4h6"/>', message:'<path d="M4 4h16v13H9l-5 4zM8 9h8m-8 4h5"/>', pause:'<path d="M9 6v12m6-12v12"/>', play:'<path d="m9 5 10 7-10 7z"/>' };
  return `<svg class="icon ${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.arrow}</svg>`;
}
export const brandImage = (lazy = false) => `<img class="brand-image" src="/assets/nova-logo-display.webp" width="64" height="64" alt=""${lazy ? ' loading="lazy" decoding="async"' : ''}>`;
export const logo = (lazy = false) => brandImage(lazy) + '<span class="wordmark">NOVA<span class="logo-lab">lab</span></span>';
export const button = (label, href, secondary = false, attrs = '') => `<a class="button ${secondary ? 'button-outline' : 'button-primary'}" href="${href}" ${attrs}>${label}${icon('diagonal')}</a>`;
const ambientArc = () => `<svg class="hero-arc" viewBox="0 0 1600 1500" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="arc-light" x1="0" y1="0" x2=".8" y2="1"><stop stop-color="#688dff" stop-opacity=".1"/><stop offset=".27" stop-color="#e4f2ff"/><stop offset=".53" stop-color="#7fa5ff"/><stop offset=".79" stop-color="#8b7edb" stop-opacity=".6"/><stop offset="1" stop-color="#7690dc" stop-opacity="0"/></linearGradient><filter id="arc-haze" x="-50%" y="-20%" width="200%" height="140%"><feGaussianBlur stdDeviation="52"/></filter><filter id="arc-bloom" x="-25%" y="-10%" width="150%" height="120%"><feGaussianBlur stdDeviation="14"/></filter><filter id="arc-core"><feGaussianBlur stdDeviation="1.1"/></filter><path id="nova-arc-path" d="M740 -80 C1240 0 1515 540 1280 1050 C1170 1280 960 1410 670 1520"/></defs><g fill="none"><use href="#nova-arc-path" stroke="#526ce2" stroke-width="140" opacity=".13" filter="url(#arc-haze)"/><use href="#nova-arc-path" stroke="url(#arc-light)" stroke-width="36" opacity=".29" filter="url(#arc-bloom)"/><use href="#nova-arc-path" stroke="url(#arc-light)" stroke-width="2.2" opacity=".58" filter="url(#arc-core)"/><use href="#nova-arc-path" stroke="url(#arc-light)" stroke-width=".65" opacity=".86"/></g></svg>`;
export function header() { return `<a class="skip-link" href="#main">Перейти к содержимому</a><header class="site-header container"><a class="brand" href="#top">${logo()}</a><nav aria-label="Основная навигация"><a href="#scenarios">Возможности</a><a href="#process">Как работаем</a><a href="#faq">Вопросы</a></nav>${button('Обсудить проект', '#contact', true)}<button class="menu-toggle" aria-label="Открыть меню" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></header><nav id="mobile-menu" class="mobile-menu" aria-label="Мобильная навигация" hidden><a href="#scenarios">Возможности</a><a href="#process">Как работаем</a><a href="#faq">Вопросы</a><a href="#contact">Обсудить проект</a></nav>`; }
function slide(s, i) {
  const products = s.title === 'Помощь покупателю' ? `<div class="product-strip" aria-label="Пример рекомендаций столов">
    <div class="product-card"><span class="product-photo product-photo-one"></span><span>Стол «Терра»<small>34 900 ₽</small></span></div>
    <div class="product-card"><span class="product-photo product-photo-two"></span><span>Стол «Ривьера»<small>42 000 ₽</small></span></div>
    <div class="product-card"><span class="product-photo product-photo-three"></span><span>Стол «Патио»<small>28 500 ₽</small></span></div>
  </div>` : '';
  return `<article class="scenario-slide ${i === 0 ? 'is-active' : ''}" data-slide="${i}" role="group" aria-roledescription="слайд" aria-label="${i + 1} из 6: ${s.title}" ${i ? 'aria-hidden="true" inert' : ''}>
  <div class="chat-panel"><span class="glass-reflection" aria-hidden="true"></span><div class="panel-header"><span class="bot-avatar" aria-hidden="true">${brandImage()}</span><div><strong>${s.botName}</strong><small>бот в MAX</small></div><span class="panel-dots" aria-hidden="true">···</span></div><div class="chat-body"><span class="chat-date">${s.category}</span><div class="bubble bot">${s.intro}</div><div class="demo-choices">${s.choices.map(c=>`<span>${c}</span>`).join('')}</div><div class="bubble user">${s.user}<span class="read-receipt" aria-hidden="true">✓✓</span></div><div class="bubble bot">${s.reply}</div><div class="bubble user">${s.last}<span class="read-receipt" aria-hidden="true">✓✓</span></div>${products}<div class="chat-status">${icon('check')}${s.status}</div></div><div class="chat-input" aria-hidden="true"><span>Сообщение</span><span>＋</span></div></div>
  <div class="staff-panel"><span class="glass-reflection" aria-hidden="true"></span><div class="staff-top"><span>${icon(s.icon)}${s.staffLabel}</span><span class="staff-count">${String(i+1).padStart(2,'0')}</span></div><div class="staff-content"><span class="tiny-label">ПАНЕЛЬ СОТРУДНИКА</span><h3>${s.staffTitle}</h3><dl>${s.rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><div class="result-note"><span class="result-icon">${icon('check')}</span>${s.result}</div>${i === 5 ? '<div class="scenario-next-step"><a href="#contact">А что должен делать ваш бот? <span aria-hidden="true">→</span></a><p>Спроектируем сценарий под ваш процесс.</p></div>' : ''}</div></div>
</article>`; }
export function carousel() { return `<section class="scenario-carousel" id="scenarios" tabindex="-1" aria-label="Возможности: демонстрационные сценарии" aria-roledescription="карусель"><h2 class="sr-only">Возможности ботов: демонстрационные сценарии</h2><div class="demo-heading"><span class="line-accent"></span> ДЕМОНСТРАЦИЯ ВОЗМОЖНОСТЕЙ <span class="demo-tag">6 сценариев</span></div><div class="demo-stage"><div class="demo-stage-content"><p class="demo-editorial">Не просто отвечает.<br><span>Запускает процессы.</span></p><div class="slides-window">${scenarios.map(slide).join('')}</div></div></div><div class="showcase-footer"><div class="carousel-bottom"><div class="scenario-caption"><span class="tiny-label">СЦЕНАРИЙ <span id="scenario-number">01</span> / 06</span><p id="scenario-title">${scenarios[0].title}</p></div><div class="carousel-controls"><button class="icon-button" id="prev-slide" aria-label="Предыдущий сценарий">${icon('arrow', 'reverse')}</button><button class="icon-button" id="next-slide" aria-label="Следующий сценарий">${icon('arrow')}</button></div></div><div class="slide-indicators" aria-label="Выбрать сценарий">${scenarios.map((s,i)=>`<button aria-label="${i+1}. ${s.title}" ${i===0?'aria-current="true"':''} data-go="${i}"><span></span></button>`).join('')}<span class="scenario-cursor" aria-hidden="true"></span></div><p class="demo-disclaimer">Примеры сценариев. Подключения обсуждаем под вашу задачу.</p></div><div class="sr-only" id="carousel-announcement" aria-live="polite" aria-atomic="true"></div></section>`; }
export function hero() { return `<section class="hero" id="top"><div class="hero-ambient" aria-hidden="true">${ambientArc()}<span class="optical-caustic optical-caustic-one"></span><span class="optical-caustic optical-caustic-two"></span><span class="optical-caustic optical-caustic-three"></span></div><div class="container"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow"><span></span>БОТЫ И АВТОМАТИЗАЦИЯ</p><h1><span class="headline-line"><span>Чат-боты в <span class="max-word">MAX</span></span></span> <span class="headline-line"><span>для бизнеса</span></span> <span class="headline-line"><span>и учреждений<span class="title-dot">.</span></span></span></h1><p class="hero-description">Разрабатываем ботов для сбора заявок, записи на услуги и автоматизации рабочих процессов.</p></div>${carousel()}<div class="hero-conversion"><div class="hero-actions">${button('Обсудить задачу','#contact',false,'data-primary-cta')}</div><p class="hero-services">Разработка <span>·</span> Интеграции <span>·</span> Поддержка</p></div></div><div class="hero-baseline"><span>Технологии.<br> Люди. Результаты.</span><a href="#process">ОТ ЗАДАЧИ К РЕЗУЛЬТАТУ ${icon('arrow')}</a></div></div></section>`; }
const steps = [ ['Разбираемся<br> в процессе','Выясняем, кто будет пользоваться ботом, какие действия нужно упростить и как оценивать результат.'], ['Проектируем<br> сценарий','Продумываем диалоги, роли сотрудников, статусы и необходимые подключения.'], ['Разрабатываем<br> и проверяем','Собираем бота и тестируем его на реальных рабочих ситуациях.'], ['Запускаем<br> и сопровождаем','Помогаем освоить работу и согласуем дальнейшую поддержку.'] ];
export function processSection() { return `<section class="process section container" id="process"><div class="section-heading"><p class="eyebrow">01 / КАК МЫ РАБОТАЕМ</p><h2>От задачи —<br> к работающему решению<span class="title-dot">.</span></h2></div><div class="steps"><div class="timeline-track" aria-hidden="true"><span></span></div>${steps.map(([t,p],i)=>`<article class="step"><div class="step-number"><span>0${i+1}</span>${icon('arrow')}</div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>`; }
export function startSection() { return `<section class="start-section container"><div class="start-panel"><div><p class="eyebrow">У КАЖДОГО ПРОЦЕССА СВОЯ ЛОГИКА</p><h2>Что обсудим<br> перед стартом</h2></div><div class="discussion-list"><p class="brief-label">ВАША ЗАДАЧА</p><article class="brief-row" tabindex="0"><span>01</span><h3>Задачи бота</h3><p>Что упростить и какой результат нужен</p></article><article class="brief-row" tabindex="0"><span>02</span><h3>Роли пользователей</h3><p>Кто обращается и кто обрабатывает запросы</p></article><article class="brief-row" tabindex="0"><span>03</span><h3>Интеграции</h3><p>Какие системы участвуют в процессе</p></article><article class="brief-row" tabindex="0"><span>04</span><h3>Сроки и сопровождение</h3><p>Приоритеты запуска и работа после него</p></article></div></div></section>`; }
export function faq() { const items = [ ['От чего зависит стоимость?', 'От сложности сценария, количества ролей, необходимых подключений и объёма разработки. После обсуждения задачи определим состав работ и подготовим оценку.'], ['Можно ли доработать сценарий после запуска?', 'Да. Бота можно развивать по мере появления новых задач. Перед изменениями обсудим их влияние на текущий процесс, объём работ и стоимость.'], ['Как устроена поддержка?', 'Формат поддержки согласуем до запуска: какие задачи входят в сопровождение, как передавать обращения и в какие сроки на них реагировать.'], ['Какие данные нужны для начала работы?', 'Описание текущего процесса, типичные запросы, роли участников и желаемый результат. Если нужны подключения, обсудим доступную документацию и условия доступа к системам.'] ]; return `<section class="faq section container" id="faq"><div><p class="eyebrow">02 / ВОПРОСЫ И ОТВЕТЫ</p><h2>По делу.<br> До старта.</h2><p class="section-description">Несколько важных деталей<br> о совместной работе.</p></div><div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}<span>${icon('plus')}</span></summary><p>${a}</p></details>`).join('')}</div></section>`; }
export function contact(config) {
  const defaultChannel = config.contacts.maxUrl ? 'max' : config.contacts.telegramUrl ? 'telegram' : 'vk';
  const messenger = (value, label, rawUrl) => {
    let url = '';
    try { const parsed = new URL(rawUrl); if (parsed.protocol === 'https:') url = parsed.href; } catch {}
    const preposition = value === 'vk' ? 'во' : 'в';
    return `<div id="contact-panel-${value}" class="contact-panel messenger-panel" role="tabpanel" aria-labelledby="contact-tab-${value}" ${value === defaultChannel ? '' : 'hidden'}>
      <span class="contact-channel-label">В ЛИЧНОМ ДИАЛОГЕ</span>
      <h3>Продолжим ${preposition} ${label}</h3>
      <p>Напишите пару слов о задаче.<br>Уточним детали в переписке.</p>
      ${url ? `<a class="button button-primary messenger-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Написать ${preposition} ${label}${icon('diagonal')}</a>` : `<button type="button" class="button button-primary messenger-link" disabled>Написать ${preposition} ${label}${icon('diagonal')}</button><p class="channel-unavailable">Ссылка на ${label} пока не добавлена.</p>`}
    </div>`;
  };
  return `<section class="contact-section" id="contact"><div class="contact-ambient" aria-hidden="true"></div><div class="contact-grid container"><span class="glass-reflection" aria-hidden="true"></span>
    <div class="contact-copy"><p class="eyebrow">03 / ДАВАЙТЕ ОБСУДИМ</p><h2>Начнём<br>с вашей задачи<span class="title-dot">.</span></h2><p>Выберите удобный канал и напишите нам.<br>Детали обсудим в переписке.</p><div class="contact-mark" aria-hidden="true">${brandImage(true)}</div></div>
    <div class="contact-options"><p class="contact-choice-label" id="contact-choice-label">Как вам удобнее?</p>
      <div class="contact-tabs" role="tablist" aria-labelledby="contact-choice-label">
        ${[['max','MAX'],['telegram','Telegram'],['vk','ВКонтакте']].map(([value,label])=>`<button type="button" role="tab" id="contact-tab-${value}" aria-controls="contact-panel-${value}" aria-selected="${value===defaultChannel}" tabindex="${value===defaultChannel?0:-1}" data-contact-tab="${value}">${label}</button>`).join('')}
      </div>
      <div class="contact-panels">
        ${messenger('max','MAX',config.contacts.maxUrl)}${messenger('telegram','Telegram',config.contacts.telegramUrl)}${messenger('vk','ВКонтакте',config.contacts.vkUrl)}
      </div>
    </div>
  </div></section>`;
}

export function footer(c) { return `<footer class="site-footer container"><div class="footer-top"><a class="brand" href="#top">${logo(true)}</a><p>Идеи. Технологии.<br> Реальный результат.</p><a class="back-top" href="#top">Наверх ${icon('diagonal')}</a></div>${c.contacts.email || c.contacts.phone ? `<div class="footer-contacts">${c.contacts.email ? `<a href="mailto:${esc(c.contacts.email)}">${esc(c.contacts.email)}</a>`:''}${c.contacts.phone ? `<a href="tel:${esc(c.contacts.phone.replace(/[^+\d]/g,''))}">${esc(c.contacts.phone)}</a>`:''}</div>`:''}<div class="footer-bottom"><span>© ${new Date().getFullYear()} NOVA lab</span>${c.legalName ? `<span>${esc(c.legalName)} ${esc(c.legalDetails)}</span>`:''}<span>Маркетинг · ИИ-контент · Разработка · Автоматизация</span></div></footer>`; }
